FROM python:3.9-slim

# 【追加】JST化 (tzdataのインストール)
RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*
ENV TZ=Asia/Tokyo

WORKDIR /app
COPY main.py .

CMD ["python", "-u", "main.py"]