FROM nginx:alpine

# 【追加】JST化 (Alpine用)
RUN apk add --no-cache tzdata
ENV TZ=Asia/Tokyo

# 設定ファイルのコピー
COPY conf.d/default.conf /etc/nginx/conf.d/default.conf

# フロントエンドファイルのコピー
COPY frontend /var/www/html