# ---------------------------------------------------------
# 1. Persistent Volume (PV)
# ---------------------------------------------------------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/minecraft"
    type: DirectoryOrCreate

---
# ---------------------------------------------------------
# 2. Persistent Volume Claim (PVC)
# ---------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# ---------------------------------------------------------
# 3. Deployment
# ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-bedrock
  labels:
    app: minecraft-bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-bedrock
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-bedrock
    spec:
      # --- Init Container: 権限修正 ---
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: minecraft-data
              mountPath: /data

      containers:
        # --- Main Container: Minecraft Bedrock ---
        - name: minecraft
          image: itzg/minecraft-bedrock-server:latest
          tty: true
          stdin: true
          ports:
            # 【修正】コンテナポートを 19134 に変更
            - containerPort: 19134
              protocol: UDP
          env:
            - name: EULA
              value: "TRUE"
            - name: GAMEMODE
              value: "survival"
            - name: DIFFICULTY
              value: "hard"
            - name: MAX_PLAYERS
              value: "20"
            - name: SERVER_NAME
              value: "Tagomori-Server"
            # 【重要】サーバーポートを 19134 に指定
            - name: SERVER_PORT
              value: "19134"
            # IPv6を無効化しIPv4のみでバインドさせる（監視安定化のため）
            - name: SERVER_PORT_V6
              value: "19135" 
            - name: TZ
              value: "Asia/Tokyo"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data

        # --- Sidecar Container: Exporter ---
        - name: exporter
          image: itzg/mc-monitor:latest
          command: 
            - "/mc-monitor"
            - "export-for-prometheus"
            - "-bedrock-servers"
            # 【修正】127.0.0.1 かつ ポート 19134 を監視
            - "127.0.0.1:19134"
          ports:
            - containerPort: 8080
              name: metrics
          env:
            - name: TZ
              value: "Asia/Tokyo"

      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc

---
# ---------------------------------------------------------
# 4. Services
# ---------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock-svc-game
spec:
  selector:
    app: minecraft-bedrock
  type: NodePort
  ports:
    - protocol: UDP
      # Serviceとしてのポートも 19134 に合わせる
      port: 19134
      targetPort: 19134
      # 外部公開ポートは 30000 のままでOK（外からは変わらずアクセス可能）
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: mc-bedrock-svc-metrics
spec:
  selector:
    app: minecraft-bedrock
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001